### ISSUE TITLE
Cannot find module 'knockout'

### ISSUE THREAD

**Issue by blbigelow** [gnab/editableCell#31]
I'm trying to use this plugin in a node-webkit project and I'm using RequireJS to load all of my dependencies. After adding editableCell to the project I get:

"Uncaught Error: Cannot find module 'knockout'", source: module.js (338)

It looks like the Require code setup doesn't work with the option of leaving "require" to nodejs and using "requirejs" instead.

**Comment by jstclair** [comment]
Hi, first - so sorry I missed this issue (didn't get a notification). Totally dropped the ball here.

I've looked at your fix. Do you have a gist or something showing where the issue originated? I see you're using RequireJS in Node - are you using something like Browserify or Webpack as well?

You may have needed to use RequireJS's shim functionality, like:

``` javascript
requirejs.config({
  paths: {
    "text": "https://cdnjs.cloudflare.com/ajax/libs/require-text/2.0.12/text",
    "knockout": "https://cdnjs.cloudflare.com/ajax/libs/knockout/3.2.0/knockout-min",
    "lodash": "https://cdnjs.cloudflare.com/ajax/libs/lodash.js/2.4.1/lodash.min",
    "editableCell": "https://cdn.rawgit.com/gnab/editableCell/v2.1.1/out/editableCell.min",
 },
, shim: {
    "editableCell": { deps: ['knockout'] }
}};
```

You can see an example if you edit/view source here:
http://jsbin.com/roheqo/1/

Might be just a doc bug for editableCell - I see we describe how to use it with RequireJS but don't mention the need for a shim.

**Comment by blbigelow** [comment]
Hi thanks for your response. I'm pretty sure I tried going the shim route, but was still unable to get things working. I ended up forcing the knockout dependency like this: https://github.com/blbigelow/editableCell/commit/67b4f844bf8716b6290ea3ec67cba9d68221571d
