### ISSUE TITLE
Clicking 3 times in field then leaving causes an exception

### ISSUE THREAD

**Issue by blbigelow** [gnab/editableCell#32]
If a user clicks at least 3 times in an editable cell field and then navigates away from that field the follow error occurs: Uncaught TypeError: undefined is not a function

**Comment by jstclair** [comment]
Thanks for reporting this; I'll look into ASAP

**Comment by jstclair** [comment]
By any chance, was this in Safari? I can easily reproduce on Safari (8.0.3)/OSX (10.10.2), but not on Chrome (41.0.2272 64bit). If not, could you let me know the specific browser you're testing on? 

I'm pretty sure fixing it for Safari would fix it for your case, but if I can test as close to your environment as possible, that would help confirm it's fixed.

The actual exception I see in Safari, if this looks familiar to you, is:

 ```
[Error] TypeError: undefined is not a function (evaluating 'cell._cellReadOnly()')
	cellIsEditable (editableCell.min.js, line 1)
	updateCellValue (editableCell.min.js, line 1)
	endEditingCell (editableCell.min.js, line 1)
	onInputBlur (editableCell.min.js, line 2)
	onInputBlur ([native code], line 0)
```

**Comment by blbigelow** [comment]
Thanks for looking into this so fast. I can repeat the same problem on Chrome(Version 40.0.2214.115 (64-bit)), but it takes 4 clicks.

You are right my original testing was on Safari 8.0.3. The tool has made my life so much easier for my current project so I am very grateful for you work on this.
